#!/usr/bin/env bash
# generate-adr-index.sh — Deterministically generate a decision record index
#
# Reads YAML frontmatter from all NNNN-*.md files in a decisions directory
# and generates a README.md index with a table of all records.
#
# Usage: bash generate-adr-index.sh [directory] [--check]
#   directory: Path to the decisions directory (default: docs/decisions)
#   --check:   Compare generated output to existing README.md and fail if different
#
# This script is READ-ONLY (except for README.md itself when not in --check mode).
# It does not install packages or make network calls.
#
# Output (when --check and no README.md to compare):
#   Structured JSON to stdout:
#   {"status":"success","results":[...],"warnings":[],"errors":[]}

set -euo pipefail

# Source shared libraries (resolve from skill script → repo root)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_SCRIPTS="${SCRIPT_DIR}/../../../scripts"
# shellcheck source=../../../scripts/lib/common.sh
source "${REPO_SCRIPTS}/lib/common.sh"

ADR_DIR="${1:-docs/decisions}"
CHECK_MODE=false

# Handle --check as first or second argument
for arg in "$@"; do
    if [ "$arg" = "--check" ]; then
        CHECK_MODE=true
    fi
done

# If first arg is --check, use default dir
if [ "${1:-}" = "--check" ]; then
    ADR_DIR="docs/decisions"
fi

# Validate directory path
ADR_DIR="$(realpath -- "$ADR_DIR" 2>/dev/null)" || {
    printf '{"status":"error","results":[],"warnings":[],"errors":["Invalid directory path: %s"]}\n' "$ADR_DIR"
    exit 1
}

if [ ! -d "$ADR_DIR" ]; then
    printf '{"status":"error","results":[],"warnings":[],"errors":["Directory does not exist: %s"]}\n' "$ADR_DIR"
    exit 1
fi

# ── Collect ADR files ────────────────────────────────────────────────

ADR_FILES=()
while IFS= read -r f; do
    ADR_FILES+=("$f")
done < <(find "$ADR_DIR" -maxdepth 1 -name '[0-9][0-9][0-9][0-9]-*.md' -type f | sort)

if [ ${#ADR_FILES[@]} -eq 0 ]; then
    printf '{"status":"success","results":[{"check":"adr_count","pass":true,"note":"No ADR files found"}],"warnings":[],"errors":[]}\n'
    exit 0
fi

# ── Count by status ──────────────────────────────────────────────────

ACCEPTED=0
PROPOSED=0
DEPRECATED=0
SUPERSEDED=0

for file in "${ADR_FILES[@]}"; do
    status=$(get_field "$file" "status")
    case "$status" in
        accepted)    ACCEPTED=$((ACCEPTED + 1)) ;;
        proposed)    PROPOSED=$((PROPOSED + 1)) ;;
        deprecated)  DEPRECATED=$((DEPRECATED + 1)) ;;
        superseded)  SUPERSEDED=$((SUPERSEDED + 1)) ;;
    esac
done

TOTAL=${#ADR_FILES[@]}

# ── Collect unique NIST controls ─────────────────────────────────────

ALL_CONTROLS=""
for file in "${ADR_FILES[@]}"; do
    controls=$(get_array_field "$file" "nist_controls")
    if [ -n "$controls" ]; then
        ALL_CONTROLS="${ALL_CONTROLS}${controls}"$'\n'
    fi
done
UNIQUE_CONTROLS=$(printf '%s' "$ALL_CONTROLS" | sort -u | grep -c '^[A-Z]' || echo "0")

# ── Generate README.md ───────────────────────────────────────────────

TODAY=$(date +%Y-%m-%d)
DIR_NAME=$(basename "$ADR_DIR")

OUTPUT="# Decision Records"$'\n'
OUTPUT+=""$'\n'
OUTPUT+="<!-- AUTO-GENERATED by federal-decision-records/scripts/generate-adr-index.sh -->"$'\n'
OUTPUT+="<!-- Do NOT edit manually — run: bash skills/federal-decision-records/scripts/generate-adr-index.sh ${DIR_NAME} -->"$'\n'
OUTPUT+=""$'\n'
OUTPUT+="| Status | Count |"$'\n'
OUTPUT+="|--------|-------|"$'\n'
OUTPUT+="| Accepted | ${ACCEPTED} |"$'\n'
OUTPUT+="| Proposed | ${PROPOSED} |"$'\n'
OUTPUT+="| Deprecated | ${DEPRECATED} |"$'\n'
OUTPUT+="| Superseded | ${SUPERSEDED} |"$'\n'
OUTPUT+="| **Total** | **${TOTAL}** |"$'\n'
OUTPUT+=""$'\n'
OUTPUT+="NIST controls referenced: ${UNIQUE_CONTROLS}"$'\n'
OUTPUT+=""$'\n'
OUTPUT+="## Records"$'\n'
OUTPUT+=""$'\n'
OUTPUT+="| # | Title | Status | Date | NIST Controls |"$'\n'
OUTPUT+="|---|-------|--------|------|---------------|"$'\n'

for file in "${ADR_FILES[@]}"; do
    filename=$(basename "$file")
    # Extract number from NNNN-title.md
    number="${filename%%-*}"
    title=$(get_field "$file" "title")
    status=$(get_field "$file" "status")
    date_val=$(get_field "$file" "date")
    controls=$(get_field "$file" "nist_controls")

    OUTPUT+="| ${number} | [${title}](./${filename}) | ${status} | ${date_val} | ${controls} |"$'\n'
done

OUTPUT+=""$'\n'
OUTPUT+="---"$'\n'
OUTPUT+="*Generated: ${TODAY}*"$'\n'

# ── Output or check ─────────────────────────────────────────────────

if [ "$CHECK_MODE" = true ]; then
    EXISTING="${ADR_DIR}/README.md"
    if [ ! -f "$EXISTING" ]; then
        echo "ERROR: ${ADR_DIR}/README.md not found"
        exit 1
    fi

    # Normalize: strip generated date for comparison
    GENERATED_NORMALIZED=$(printf '%s' "$OUTPUT" | grep -v '^\*Generated:')
    EXISTING_NORMALIZED=$(grep -v '^\*Generated:' "$EXISTING")

    if [ "$GENERATED_NORMALIZED" != "$EXISTING_NORMALIZED" ]; then
        echo "ERROR: ${ADR_DIR}/README.md is out of date. Run: bash skills/federal-decision-records/scripts/generate-adr-index.sh ${ADR_DIR}"
        echo ""
        echo "Diff:"
        diff <(printf '%s\n' "$EXISTING_NORMALIZED") <(printf '%s\n' "$GENERATED_NORMALIZED") || true
        exit 1
    fi

    echo "OK: ${ADR_DIR}/README.md is up to date"
    exit 0
fi

# Write README.md
printf '%s' "$OUTPUT" > "${ADR_DIR}/README.md"
echo "Generated ${ADR_DIR}/README.md (${TOTAL} records, ${UNIQUE_CONTROLS} unique NIST controls)"
