#!/bin/sh
# generate-index.sh — Deterministically generate INDEX.yaml from source files

set -eu

SCRIPT_DIR=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)
REPO_ROOT=$(CDPATH='' cd -- "${SCRIPT_DIR}/.." && pwd -P)

# shellcheck source=scripts/lib/common.sh
. "${SCRIPT_DIR}/lib/common.sh"
# shellcheck source=scripts/config.sh
. "${SCRIPT_DIR}/config.sh"

CHECK_MODE="false"
TMP_DIR=$(create_temp_dir)
CONTENT_FILES="${TMP_DIR}/content-files.list"
TIER1_FILES="${TMP_DIR}/tier1.list"
TIER2_FILES="${TMP_DIR}/tier2.list"
TIER3_FILES="${TMP_DIR}/tier3.list"
SKILL_DIRS="${TMP_DIR}/skill-dirs.list"
OUTPUT_FILE="${TMP_DIR}/INDEX.yaml"
ALL_CONTROLS="${TMP_DIR}/controls.list"
ALL_FRAMEWORKS="${TMP_DIR}/frameworks.list"

cleanup() {
	rm -rf "$TMP_DIR"
}
trap cleanup EXIT HUP INT TERM

[ "${1:-}" = "--check" ] && CHECK_MODE="true"

array_values_to_yaml_list() {
	indent=$1
	values=$2

	printf '%s\n' "$values" | sed '/^$/d' | while IFS= read -r item; do
		printf '%s- "%s"\n' "$indent" "$item"
	done
}

append_doc_block() {
	file=$1

	path=${file#./}
	title=$(trim_quotes "$(get_field "$file" "title" || true)")
	desc=$(trim_quotes "$(get_field "$file" "description" || true)")
	status=$(trim_quotes "$(get_field "$file" "status" || true)")
	tier=$(trim_quotes "$(get_field "$file" "tier" || true)")
	last_updated=$(trim_quotes "$(get_field "$file" "last_updated" || true)")
	audience=$(trim_quotes "$(get_field "$file" "audience" || true)")
	load_priority=$(trim_quotes "$(get_field "$file" "load_priority" || true)")
	review_cycle=$(trim_quotes "$(get_field "$file" "review_cycle" || true)")
	controls=$(get_array_field "$file" "nist_controls" || true)
	frameworks=$(get_array_field "$file" "frameworks" || true)

	{
		printf '  - path: "%s"\n' "$path"
		printf '    title: "%s"\n' "$title"
		printf '    description: "%s"\n' "$desc"
		printf '    status: "%s"\n' "$status"
		printf '    tier: "%s"\n' "$tier"

		[ -n "$load_priority" ] && printf '    load_priority: "%s"\n' "$load_priority"
		[ -n "$last_updated" ] && printf '    last_updated: "%s"\n' "$last_updated"
		[ -n "$audience" ] && printf '    audience: "%s"\n' "$audience"
		[ -n "$review_cycle" ] && printf '    review_cycle: "%s"\n' "$review_cycle"

		if [ -n "$controls" ]; then
			printf '    nist_controls:\n'
			printf '%s\n' "$controls" | while IFS= read -r control; do
				[ -n "$control" ] || continue
				printf '      - "%s"\n' "$(trim_quotes "$(printf '%s' "$control" | sed 's/^[[:space:]]*//')")"
			done
		else
			printf '    nist_controls: []\n'
		fi

		if [ -n "$frameworks" ]; then
			printf '    frameworks:\n'
			printf '%s\n' "$frameworks" | while IFS= read -r framework; do
				[ -n "$framework" ] || continue
				printf '      - "%s"\n' "$(trim_quotes "$(printf '%s' "$framework" | sed 's/^[[:space:]]*//')")"
			done
		else
			printf '    frameworks: []\n'
		fi

		printf '\n'
	} >> "$OUTPUT_FILE"
}

count_unique_from_listed_frontmatter_field() {
	input_list=$1
	field_name=$2
	output_list=$3

	: > "$output_list"

	if [ -s "$input_list" ]; then
		while IFS= read -r file || [ -n "$file" ]; do
			[ -n "$file" ] || continue
			get_array_field "$file" "$field_name" || true
		done < "$input_list" >> "$output_list"
	fi

	if [ -s "$output_list" ]; then
		sed 's/^[[:space:]]*//' "$output_list" | sed '/^$/d' | LC_ALL=C sort -u | grep -c .
	else
		printf '0\n'
	fi
}

cd "$REPO_ROOT" || die "Failed to enter repo root"

find . \
	\( -name '*.md' -o -name '*.md.template' -o -name '*.md.example' \) \
	-not -path './.git/*' \
	-not -path './.github/*' \
	-not -path './node_modules/*' \
	-not -path './skills/*' \
	-not -name 'CONTRIBUTING.md' \
	-not -name 'CHANGELOG.md' \
	-not -name 'README.md' \
	-not -name 'SECURITY.md' \
	-not -name 'LICENSE' \
	| LC_ALL=C sort > "$CONTENT_FILES"

: > "$TIER1_FILES"
: > "$TIER2_FILES"
: > "$TIER3_FILES"

if [ -s "$CONTENT_FILES" ]; then
	while IFS= read -r file || [ -n "$file" ]; do
		[ -n "$file" ] || continue
		tier=$(trim_quotes "$(get_field "$file" "tier" || true)")
		case "$tier" in
			1) printf '%s\n' "$file" >> "$TIER1_FILES" ;;
			2) printf '%s\n' "$file" >> "$TIER2_FILES" ;;
			3) printf '%s\n' "$file" >> "$TIER3_FILES" ;;
		esac
	done < "$CONTENT_FILES"
fi

if [ -d "skills" ]; then
	find skills -mindepth 1 -maxdepth 1 -type d | LC_ALL=C sort > "$SKILL_DIRS"
else
	: > "$SKILL_DIRS"
fi

TOTAL_DOCS=$(count_lines "$CONTENT_FILES")
TOTAL_SKILLS=$(count_lines "$SKILL_DIRS")
TIER1_COUNT=$(count_lines "$TIER1_FILES")
TIER2_COUNT=$(count_lines "$TIER2_FILES")
TIER3_COUNT=$(count_lines "$TIER3_FILES")
UNIQUE_CONTROLS=$(count_unique_from_listed_frontmatter_field "$CONTENT_FILES" "nist_controls" "$ALL_CONTROLS")
UNIQUE_FRAMEWORKS=$(count_unique_from_listed_frontmatter_field "$CONTENT_FILES" "frameworks" "$ALL_FRAMEWORKS")
TODAY=$(date +%Y-%m-%d)

{
	printf '# Federal Agentic AI Playbook — Document Index\n'
	printf '#\n'
	printf '# AUTO-GENERATED by scripts/generate-index.sh\n'
	printf '# Do NOT edit manually — run: sh scripts/generate-index.sh\n'
	printf '#\n'
	printf '# Schema version: 1.0\n'
	printf '# Last generated: %s\n' "$TODAY"
	printf '\n'
	printf 'schema_version: "1.0"\n'
	printf 'generated: "%s"\n' "$TODAY"
	printf 'repo: "GSA-TTS/agentic-ai-playbook"\n'
	printf 'scope: "FIPS Moderate | Single-agent | Internal enterprise"\n'
	printf '\n'
	printf 'frontmatter_schema:\n'
	printf '  required:\n'
	array_values_to_yaml_list "    " "$REQUIRED_FRONTMATTER_FIELDS"
	printf '  optional:\n'
	array_values_to_yaml_list "    " "$OPTIONAL_FRONTMATTER_FIELDS"
	printf '  status_values:\n'
	array_values_to_yaml_list "    " "$DOC_STATUS_VALUES"
	printf '  tier_values:\n'
	array_values_to_yaml_list "    " "$DOC_TIER_VALUES"
	printf '  audience_values:\n'
	array_values_to_yaml_list "    " "$DOC_AUDIENCE_VALUES"
	printf '  load_priority_values:\n'
	array_values_to_yaml_list "    " "$DOC_LOAD_PRIORITY_VALUES"
	printf '  review_cycle_values:\n'
	array_values_to_yaml_list "    " "$DOC_REVIEW_CYCLE_VALUES"
	printf 'documents:\n'
} > "$OUTPUT_FILE"

if [ -s "$TIER1_FILES" ]; then
	printf '  # Tier 1 — Core playbook\n' >> "$OUTPUT_FILE"
	while IFS= read -r file || [ -n "$file" ]; do
		[ -n "$file" ] || continue
		append_doc_block "$file"
	done < "$TIER1_FILES"
fi

if [ -s "$TIER2_FILES" ]; then
	printf '  # Tier 2 — Supporting documentation\n' >> "$OUTPUT_FILE"
	while IFS= read -r file || [ -n "$file" ]; do
		[ -n "$file" ] || continue
		append_doc_block "$file"
	done < "$TIER2_FILES"
fi

if [ -s "$TIER3_FILES" ]; then
	printf '  # Tier 3 — Templates, checklists, examples\n' >> "$OUTPUT_FILE"
	while IFS= read -r file || [ -n "$file" ]; do
		[ -n "$file" ] || continue
		append_doc_block "$file"
	done < "$TIER3_FILES"
fi

printf 'skills:\n' >> "$OUTPUT_FILE"

if [ -s "$SKILL_DIRS" ]; then
	while IFS= read -r skill_dir || [ -n "$skill_dir" ]; do
		[ -n "$skill_dir" ] || continue

		skill_name=$(basename -- "$skill_dir")
		skill_file="${skill_dir}/SKILL.md"
		[ -f "$skill_file" ] || continue

		skill_desc=$(trim_quotes "$(get_field "$skill_file" "description" || true)")
		printf '  - name: "%s"\n' "$skill_name" >> "$OUTPUT_FILE"
		printf '    path: "%s"\n' "$skill_file" >> "$OUTPUT_FILE"
		[ -n "$skill_desc" ] && printf '    description: "%s"\n' "$skill_desc" >> "$OUTPUT_FILE"

		if [ -d "${skill_dir}/scripts" ]; then
			script_list="${TMP_DIR}/skill-scripts.$$.list"
			find "${skill_dir}/scripts" -type f \( -name '*.sh' -o -name '*.py' \) | LC_ALL=C sort > "$script_list"
			if [ -s "$script_list" ]; then
				printf '    has_scripts: true\n' >> "$OUTPUT_FILE"
				printf '    scripts:\n' >> "$OUTPUT_FILE"
				while IFS= read -r script_path || [ -n "$script_path" ]; do
					[ -n "$script_path" ] || continue
					printf '      - "%s"\n' "$script_path" >> "$OUTPUT_FILE"
				done < "$script_list"
			else
				printf '    has_scripts: false\n' >> "$OUTPUT_FILE"
				printf '    scripts: []\n' >> "$OUTPUT_FILE"
			fi
			rm -f "$script_list"
		else
			printf '    has_scripts: false\n' >> "$OUTPUT_FILE"
			printf '    scripts: []\n' >> "$OUTPUT_FILE"
		fi

		printf '\n' >> "$OUTPUT_FILE"
	done < "$SKILL_DIRS"
fi

{
	printf 'stats:\n'
	printf '  total_documents: %s\n' "$TOTAL_DOCS"
	printf '  total_skills: %s\n' "$TOTAL_SKILLS"
	printf '  tier_1_core: %s\n' "$TIER1_COUNT"
	printf '  tier_2_supporting: %s\n' "$TIER2_COUNT"
	printf '  tier_3_templates: %s\n' "$TIER3_COUNT"
	printf '  total_nist_controls_referenced: %s\n' "$UNIQUE_CONTROLS"
	printf '  frameworks_covered: %s\n' "$UNIQUE_FRAMEWORKS"
} >> "$OUTPUT_FILE"

if [ "$CHECK_MODE" = "true" ]; then
	[ -f "${REPO_ROOT}/INDEX.yaml" ] || die "INDEX.yaml not found"

	generated_normalized="${TMP_DIR}/generated.normalized"
	existing_normalized="${TMP_DIR}/existing.normalized"

	grep -v '^generated:' "$OUTPUT_FILE" | grep -v '^# Last generated:' > "$generated_normalized"
	grep -v '^generated:' "${REPO_ROOT}/INDEX.yaml" | grep -v '^# Last generated:' > "$existing_normalized"

	if ! cmp -s "$generated_normalized" "$existing_normalized"; then
		printf 'Error: INDEX.yaml is out of date. Run: sh scripts/generate-index.sh\n' >&2
		diff -u "$existing_normalized" "$generated_normalized" || true
		exit 1
	fi

	log "OK: INDEX.yaml is up to date"
	exit 0
fi

mv "$OUTPUT_FILE" "${REPO_ROOT}/INDEX.yaml" || die "Failed to write INDEX.yaml"
log "Generated INDEX.yaml (${TOTAL_DOCS} documents, ${TOTAL_SKILLS} skills, ${UNIQUE_CONTROLS} unique NIST controls)"
