#!/usr/bin/env bash
# generate-index.sh — Deterministically generate INDEX.yaml from source files
#
# Reads YAML frontmatter from all content .md files and scans skill
# directories to produce a consistent INDEX.yaml. This prevents drift
# by deriving ALL metadata from source files.
#
# Usage: bash scripts/generate-index.sh [--check]
#   --check: Compare generated output to existing INDEX.yaml and fail if different
#
# This script is READ-ONLY (except for INDEX.yaml itself when not in --check mode).
# It does not install packages or make network calls.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CHECK_MODE=false

if [ "${1:-}" = "--check" ]; then
    CHECK_MODE=true
fi

# Source shared libraries
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "${SCRIPT_DIR}/lib/common.sh"
# shellcheck source=config.sh
source "${SCRIPT_DIR}/config.sh"

# Count unique NIST controls from frontmatter across all documents
count_unique_nist_controls() {
    local all_controls=""
    for file in "$@"; do
        local controls
        controls=$(get_array_field "$file" "nist_controls")
        if [ -n "$controls" ]; then
            all_controls="${all_controls}${controls}"$'\n'
        fi
    done
    printf '%s' "$all_controls" | sort -u | grep -c '^[A-Z]' || echo "0"
}

# Count unique frameworks across all documents
count_unique_frameworks() {
    local all_frameworks=""
    for file in "$@"; do
        local frameworks
        frameworks=$(get_array_field "$file" "frameworks")
        if [ -n "$frameworks" ]; then
            all_frameworks="${all_frameworks}${frameworks}"$'\n'
        fi
    done
    printf '%s' "$all_frameworks" | sed 's/^[[:space:]]*//' | sort -u | grep -c '.' || echo "0"
}

# ── Collect content files (same find as validate-docs.sh) ───────────

cd "$REPO_ROOT"

CONTENT_FILES=()
while IFS= read -r f; do
    CONTENT_FILES+=("$f")
done < <(find . \( -name '*.md' -o -name '*.md.template' -o -name '*.md.example' \) \
    -not -path './.git/*' \
    -not -path './.github/*' \
    -not -path './node_modules/*' \
    -not -path './skills/*' \
    -not -name 'CONTRIBUTING.md' \
    -not -name 'CHANGELOG.md' \
    -not -name 'README.md' \
    -not -name 'SECURITY.md' \
    -not -name 'LICENSE' \
    | sort)

# ── Classify documents by tier ──────────────────────────────────────

TIER1_FILES=()
TIER2_FILES=()
TIER3_FILES=()

for file in "${CONTENT_FILES[@]}"; do
    tier=$(get_field "$file" "tier")
    case "$tier" in
        1) TIER1_FILES+=("$file") ;;
        2) TIER2_FILES+=("$file") ;;
        3) TIER3_FILES+=("$file") ;;
    esac
done

# ── Collect skill directories ───────────────────────────────────────

SKILL_DIRS=()
if [ -d "skills" ]; then
    while IFS= read -r d; do
        SKILL_DIRS+=("$d")
    done < <(find skills -mindepth 1 -maxdepth 1 -type d | sort)
fi

# ── Compute stats ───────────────────────────────────────────────────

TOTAL_DOCS=${#CONTENT_FILES[@]}
TOTAL_SKILLS=${#SKILL_DIRS[@]}
TIER1_COUNT=${#TIER1_FILES[@]}
TIER2_COUNT=${#TIER2_FILES[@]}
TIER3_COUNT=${#TIER3_FILES[@]}
UNIQUE_CONTROLS=$(count_unique_nist_controls "${CONTENT_FILES[@]}")
UNIQUE_FRAMEWORKS=$(count_unique_frameworks "${CONTENT_FILES[@]}")

# ── Generate YAML ───────────────────────────────────────────────────

TODAY=$(date +%Y-%m-%d)

OUTPUT=""
OUTPUT+="# Federal Agentic AI Guidance — Document Index"$'\n'
OUTPUT+="#"$'\n'
OUTPUT+="# AUTO-GENERATED by scripts/generate-index.sh"$'\n'
OUTPUT+="# Do NOT edit manually — run: bash scripts/generate-index.sh"$'\n'
OUTPUT+="#"$'\n'
OUTPUT+="# Agents SHOULD read this file to understand the repository structure"$'\n'
OUTPUT+="# before making changes that span multiple documents."$'\n'
OUTPUT+="#"$'\n'
OUTPUT+="# Schema version: 1.0"$'\n'
OUTPUT+="# Last generated: ${TODAY}"$'\n'
OUTPUT+=""$'\n'
OUTPUT+="schema_version: \"1.0\""$'\n'
OUTPUT+="generated: \"${TODAY}\""$'\n'
OUTPUT+="repo: \"cloud-gov/federal-agentic-ai-guidance\""$'\n'
OUTPUT+="scope: \"FIPS Moderate | Single-agent | Internal enterprise\""$'\n'
OUTPUT+=""$'\n'
# Build schema arrays from config.sh constants
REQUIRED_QUOTED=$(printf ', "%s"' "${REQUIRED_FRONTMATTER_FIELDS[@]}")
REQUIRED_QUOTED="[${REQUIRED_QUOTED:2}]"
OPTIONAL_QUOTED=$(printf ', "%s"' "${OPTIONAL_FRONTMATTER_FIELDS[@]}")
OPTIONAL_QUOTED="[${OPTIONAL_QUOTED:2}]"
STATUS_QUOTED=$(printf ', "%s"' "${DOC_STATUS_VALUES[@]}")
STATUS_QUOTED="[${STATUS_QUOTED:2}]"
AUDIENCE_QUOTED=$(printf ', "%s"' "${DOC_AUDIENCE_VALUES[@]}")
AUDIENCE_QUOTED="[${AUDIENCE_QUOTED:2}]"
REVIEW_QUOTED=$(printf ', "%s"' "${DOC_REVIEW_CYCLE_VALUES[@]}")
REVIEW_QUOTED="[${REVIEW_QUOTED:2}]"
LOAD_PRIORITY_QUOTED=$(printf ', "%s"' "${DOC_LOAD_PRIORITY_VALUES[@]}")
LOAD_PRIORITY_QUOTED="[${LOAD_PRIORITY_QUOTED:2}]"

OUTPUT+="# Frontmatter schema — all .md content files MUST include at minimum:"$'\n'
OUTPUT+="#   $(printf '%s (required), ' "${REQUIRED_FRONTMATTER_FIELDS[@]}" | sed 's/, $//')"$'\n'
OUTPUT+="# Optional: $(printf '%s, ' "${OPTIONAL_FRONTMATTER_FIELDS[@]}" | sed 's/, $//')"$'\n'
OUTPUT+="frontmatter_schema:"$'\n'
OUTPUT+="  required: ${REQUIRED_QUOTED}"$'\n'
OUTPUT+="  optional: ${OPTIONAL_QUOTED}"$'\n'
OUTPUT+="  status_values: ${STATUS_QUOTED}"$'\n'
OUTPUT+="  tier_values:"$'\n'
OUTPUT+="    1: \"Core guidance — authoritative rules and control mappings\""$'\n'
OUTPUT+="    2: \"Supporting documentation — how-to guides and setup instructions\""$'\n'
OUTPUT+="    3: \"Templates and checklists — reusable artifacts for projects\""$'\n'
OUTPUT+="  audience_values: ${AUDIENCE_QUOTED}"$'\n'
OUTPUT+="  load_priority_values: ${LOAD_PRIORITY_QUOTED}"$'\n'
OUTPUT+="  review_cycle_values: ${REVIEW_QUOTED}"$'\n'
OUTPUT+=""$'\n'
OUTPUT+="# Document inventory"$'\n'
OUTPUT+="documents:"$'\n'

# Helper to emit a document entry
emit_doc() {
    local file="$1"
    local path="${file#./}"
    local title desc status tier last_updated audience load_priority review_cycle
    title=$(get_field "$file" "title")
    desc=$(get_field "$file" "description")
    status=$(get_field "$file" "status")
    tier=$(get_field "$file" "tier")
    last_updated=$(get_field "$file" "last_updated")
    audience=$(get_field "$file" "audience")
    load_priority=$(get_field "$file" "load_priority")
    review_cycle=$(get_field "$file" "review_cycle")

    OUTPUT+="  - path: \"${path}\""$'\n'
    OUTPUT+="    title: \"${title}\""$'\n'
    OUTPUT+="    description: \"${desc}\""$'\n'
    OUTPUT+="    status: ${status}"$'\n'
    OUTPUT+="    tier: ${tier}"$'\n'
    if [ -n "$load_priority" ]; then
        OUTPUT+="    load_priority: ${load_priority}"$'\n'
    fi
    if [ -n "$last_updated" ]; then
        OUTPUT+="    last_updated: \"${last_updated}\""$'\n'
    fi
    if [ -n "$audience" ]; then
        OUTPUT+="    audience: ${audience}"$'\n'
    fi

    # Count nist_controls from frontmatter
    local controls
    controls=$(get_array_field "$file" "nist_controls")
    if [ -n "$controls" ]; then
        local count
        count=$(printf '%s\n' "$controls" | grep -c '^[A-Z]' || echo "0")
        OUTPUT+="    nist_controls_count: ${count}"$'\n'
    fi

    if [ -n "$review_cycle" ]; then
        OUTPUT+="    review_cycle: ${review_cycle}"$'\n'
    fi
    OUTPUT+=""$'\n'
}

# Emit Tier 1
if [ ${#TIER1_FILES[@]} -gt 0 ]; then
    OUTPUT+="  # ── Tier 1: Core Guidance ────────────────────────────────────────"$'\n'
    for file in "${TIER1_FILES[@]}"; do
        emit_doc "$file"
    done
fi

# Emit Tier 2
if [ ${#TIER2_FILES[@]} -gt 0 ]; then
    OUTPUT+="  # ── Tier 2: Supporting Documentation ─────────────────────────────"$'\n'
    for file in "${TIER2_FILES[@]}"; do
        emit_doc "$file"
    done
fi

# Emit Tier 3
if [ ${#TIER3_FILES[@]} -gt 0 ]; then
    OUTPUT+="  # ── Tier 3: Templates, Checklists, and Examples ──────────────────"$'\n'
    for file in "${TIER3_FILES[@]}"; do
        emit_doc "$file"
    done
fi

# ── Skills section ──────────────────────────────────────────────────

if [ ${#SKILL_DIRS[@]} -gt 0 ]; then
    OUTPUT+="# Agent Skills — executable compliance procedures (Agent Skills format)"$'\n'
    OUTPUT+="# Skills provide step-by-step workflows agents can follow."$'\n'
    OUTPUT+="# They reference policy docs by path+section — no policy duplication."$'\n'
    OUTPUT+="# Format: https://agentskills.io/specification"$'\n'
    OUTPUT+="skills:"$'\n'

    for skill_dir in "${SKILL_DIRS[@]}"; do
        local_name=$(basename "$skill_dir")
        skill_file="${skill_dir}/SKILL.md"

        if [ ! -f "$skill_file" ]; then
            continue
        fi

        # Read skill frontmatter
        local_desc=$(get_field "$skill_file" "description")

        OUTPUT+="  - name: ${local_name}"$'\n'
        OUTPUT+="    path: \"${skill_file}\""$'\n'
        OUTPUT+="    description: \"${local_desc}\""$'\n'

        # Check for scripts
        if [ -d "${skill_dir}/scripts" ]; then
            local_scripts=()
            while IFS= read -r s; do
                local_scripts+=("$s")
            done < <(find "${skill_dir}/scripts" -type f \( -name '*.sh' -o -name '*.py' \) | sort)

            if [ ${#local_scripts[@]} -gt 0 ]; then
                OUTPUT+="    has_scripts: true"$'\n'
                OUTPUT+="    scripts:"$'\n'
                for script in "${local_scripts[@]}"; do
                    OUTPUT+="      - \"${script}\""$'\n'
                done
            else
                OUTPUT+="    has_scripts: false"$'\n'
            fi
        else
            OUTPUT+="    has_scripts: false"$'\n'
        fi
        OUTPUT+=""$'\n'
    done
fi

# ── Stats section ───────────────────────────────────────────────────

OUTPUT+="stats:"$'\n'
OUTPUT+="  total_documents: ${TOTAL_DOCS}"$'\n'
OUTPUT+="  total_skills: ${TOTAL_SKILLS}"$'\n'
OUTPUT+="  tier_1_core: ${TIER1_COUNT}"$'\n'
OUTPUT+="  tier_2_supporting: ${TIER2_COUNT}"$'\n'
OUTPUT+="  tier_3_templates: ${TIER3_COUNT}"$'\n'
OUTPUT+="  total_nist_controls_referenced: ${UNIQUE_CONTROLS}"$'\n'
OUTPUT+="  frameworks_covered: ${UNIQUE_FRAMEWORKS}"$'\n'

# ── Output or check ─────────────────────────────────────────────────

if [ "$CHECK_MODE" = true ]; then
    # Compare generated output with existing INDEX.yaml (ignoring generated date)
    EXISTING="${REPO_ROOT}/INDEX.yaml"
    if [ ! -f "$EXISTING" ]; then
        echo "ERROR: INDEX.yaml not found"
        exit 1
    fi

    # Normalize: strip the generated date line for comparison (it changes daily)
    GENERATED_NORMALIZED=$(printf '%s' "$OUTPUT" | grep -v '^generated:' | grep -v '^# Last generated:')
    EXISTING_NORMALIZED=$(grep -v '^generated:' "$EXISTING" | grep -v '^# Last generated:')

    if [ "$GENERATED_NORMALIZED" != "$EXISTING_NORMALIZED" ]; then
        echo "ERROR: INDEX.yaml is out of date. Run: bash scripts/generate-index.sh"
        echo ""
        echo "Diff:"
        diff <(printf '%s\n' "$EXISTING_NORMALIZED") <(printf '%s\n' "$GENERATED_NORMALIZED") || true
        exit 1
    fi

    echo "OK: INDEX.yaml is up to date"

    # Also check README.md skills table if markers exist
    README="${REPO_ROOT}/README.md"
    if [ -f "$README" ] && grep -q "GENERATED:SKILLS_TABLE:START" "$README"; then
        # Build expected table
        EXPECTED_TABLE="| Skill | Purpose | Scripts? |"$'\n'
        EXPECTED_TABLE+="|-------|---------|----------|"

        for skill_dir in "${SKILL_DIRS[@]}"; do
            local_name=$(basename "$skill_dir")
            skill_file="${skill_dir}/SKILL.md"
            [ -f "$skill_file" ] || continue
            local_desc=$(get_field "$skill_file" "description")
            short_desc=$(printf '%s' "$local_desc" | sed 's/\. [A-Z].*//')
            if [ ${#short_desc} -gt 90 ]; then
                short_desc=$(printf '%s' "$short_desc" | head -c 87 | sed 's/ [^ ]*$//')...
            fi
            if [ -d "${skill_dir}/scripts" ] && find "${skill_dir}/scripts" -type f \( -name '*.sh' -o -name '*.py' \) 2>/dev/null | grep -q .; then
                has_scripts="Yes"
            else
                has_scripts="No"
            fi
            EXPECTED_TABLE+=$'\n'"| \`${local_name}\` | ${short_desc} | ${has_scripts} |"
        done

        # Extract current table from README (between markers)
        CURRENT_TABLE=$(sed -n '/GENERATED:SKILLS_TABLE:START/,/GENERATED:SKILLS_TABLE:END/p' "$README" | grep '|')

        if [ "$CURRENT_TABLE" != "$EXPECTED_TABLE" ]; then
            echo "ERROR: README.md skills table is out of date. Run: bash scripts/generate-index.sh"
            exit 1
        fi
        echo "OK: README.md skills table is up to date"
    fi

    exit 0
fi

# Write INDEX.yaml
printf '%s' "$OUTPUT" > "${REPO_ROOT}/INDEX.yaml"
echo "Generated INDEX.yaml (${TOTAL_DOCS} documents, ${TOTAL_SKILLS} skills, ${UNIQUE_CONTROLS} unique NIST controls)"

# ── Inject skills table into README.md ─────────────────────────────

README="${REPO_ROOT}/README.md"
START_MARKER="<!-- GENERATED:SKILLS_TABLE:START"
END_MARKER="<!-- GENERATED:SKILLS_TABLE:END -->"

if [ -f "$README" ] && grep -q "$START_MARKER" "$README"; then
    # Build skills table from collected skill data
    SKILLS_TABLE="<!-- GENERATED:SKILLS_TABLE:START — do not edit, run: bash scripts/generate-index.sh -->"$'\n'
    SKILLS_TABLE+="| Skill | Purpose | Scripts? |"$'\n'
    SKILLS_TABLE+="|-------|---------|----------|"$'\n'

    for skill_dir in "${SKILL_DIRS[@]}"; do
        local_name=$(basename "$skill_dir")
        skill_file="${skill_dir}/SKILL.md"
        [ -f "$skill_file" ] || continue

        # Get short description for table: first sentence (split on ". [A-Z]" to
        # avoid splitting filenames like AGENTS.md), then truncate at word boundary
        local_desc=$(get_field "$skill_file" "description")
        short_desc=$(printf '%s' "$local_desc" | sed 's/\. [A-Z].*//')
        # If still > 90 chars, truncate at word boundary
        if [ ${#short_desc} -gt 90 ]; then
            short_desc=$(printf '%s' "$short_desc" | head -c 87 | sed 's/ [^ ]*$//')...
        fi

        # Check for scripts
        if [ -d "${skill_dir}/scripts" ] && find "${skill_dir}/scripts" -type f \( -name '*.sh' -o -name '*.py' \) 2>/dev/null | grep -q .; then
            has_scripts="Yes"
        else
            has_scripts="No"
        fi

        SKILLS_TABLE+="| \`${local_name}\` | ${short_desc} | ${has_scripts} |"$'\n'
    done

    SKILLS_TABLE+="$END_MARKER"

    # Replace content between markers
    # Write table to temp file, then use awk to inject
    TABLE_FILE=$(mktemp)
    printf '%s\n' "$SKILLS_TABLE" > "$TABLE_FILE"

    awk -v tablefile="$TABLE_FILE" '
        /GENERATED:SKILLS_TABLE:START/ { skip=1; while ((getline line < tablefile) > 0) print line; close(tablefile); next }
        /GENERATED:SKILLS_TABLE:END/ { skip=0; next }
        !skip { print }
    ' "$README" > "${README}.tmp" && mv "${README}.tmp" "$README"

    rm -f "$TABLE_FILE"
    echo "Injected skills table into README.md"
fi
